- name: Add ESXi host to vcenter
  hosts: all
  gather_facts: False
  become: no
  vars:
    datacenter: cloud
    folder: /cloud/testhost

  tasks:
    - name: add ESXi Host to vCenter under a specific folder
      vmware_host:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter_name: "{{ datacenter }}"
        folder: "{{ folder }}"
        esxi_hostname: '{{ ansible_host }}'
        esxi_username: '{{ ansible_user | default(ansible_ssh_user) }}'
        esxi_password: '{{ ansible_password }}'
        state: present
        add_connected: True
      delegate_to: localhost