- name: import templates to vcenter
  hosts: all
  gather_facts: no
  become: no
  vars:
    network_host: 192.168.1.103
    network_path: /mnt/vault/work/install
    ova_files:
      - windows-10-1809-ovf.ova
      - rhel76-x64-bigdisk.ova
      - windows-2016-standard-core-ovf.ova
      - centos75-x64-bigdisk_v4.ova
      - windows-2016-ovf.ova
      - windows-2016-datacenter-ovf.ova

  roles:
    - role: vcenter-deploy-ova-template
      run_once: yes
