---

- name: obtain thumbprint
  command: openssl x509 -in /etc/vmware/ssl/rui.crt -fingerprint -sha1 -noout
  register: esxi_ssl_thumbprint

- name: add ESXi Host to vCenter under a specific folder
  vmware_host:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter_name: "{{ vcenter_datacenter }}"
    cluster_name: "{{ vcenter_cluster }}"
    esxi_hostname: "{{ ansible_host }}"
    esxi_username: "{{ ansible_user | default(ansible_ssh_user) | default('root') | urlencode }}"
    esxi_password: "{{ ansible_password }}"
    esxi_ssl_thumbprint: "{{ esxi_ssl_thumbprint.stdout }}"
    state: present
    add_connected: True
  delegate_to: localhost