---

- name: ensure datacenter exists
  vmware_datacenter:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter_name: '{{ vcenter_datacenter }}'
    state: present
  delegate_to: localhost

- name: ensure cluster exists
  vmware_cluster:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter_name: '{{ vcenter_datacenter }}'
    cluster_name: '{{ vcenter_cluster }}'
    enable_ha: '{{ enable_ha}}'
    enable_drs: '{{ enable_drs }}'
    enable_vsan: '{{ enable_vsan }}'
    state: present
  delegate_to: localhost

- name: create resource pools
  vmware_resource_pool:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    cluster: '{{ vcenter_cluster }}'
    resource_pool: '{{ item }}'
    state: present
  delegate_to: localhost
  loop: "{{ vcenter_resource_pools }}"

- name: create folders
  vcenter_folder:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    folder_name: "{{ item }}"
    folder_type: vm
    state: present
  delegate_to: localhost
  loop: "{{ vcenter_vm_folders }}"

- name: Add a new vCenter license
  vcenter_license:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    license: "{{ vcenter_license }}"
    state: present
  delegate_to: localhost
  when:
    - vcenter_license is defined
    - vcenter_license

- name: move vcenter to infra resource pool
  vmware_guest_move:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    name: "{{ vcenter_appliance_name }}"
    dest_folder: /Resources/infra
  delegate_to: localhost