---

- name: test vcenter connectivity
  uri:
    url: https://{{ vcenter_fqdn }}
    return_content: no
    validate_certs: no
  register: response
  ignore_errors: yes

- debug:
    var: response

- name: gather information about vms and templates
  vmware_vm_facts:
    hostname: "{{ ansible_host }}"
    username: root
    password: "{{ ansible_password | default(ansible_ssh_password) }}"
    validate_certs: no
  delegate_to: localhost
  register: vm_facts

- block:

    - include_tasks: mount_nfs.yml

    - include_tasks: deploy.yml

    - include_tasks: unmount_nfs.yml

    - include_tasks: wait.yml

  when:
    - vcenter_appliance_name not in vm_facts.virtual_machines | list